"""mmCIF metadata generation and manipulation.

This module handles the creation and addition of metadata fields to mmCIF (macromolecular
Crystallographic Information File) files generated by AlphaFold 3. It includes:
- AlphaFold-specific metadata (software version, citation, authors)
- ModelCIF compliance information
- License and disclaimer text
- Quality assessment metrics (pLDDT scores)
- Model provenance and methodology details

The metadata follows the ModelCIF dictionary specification and includes proper
attribution to the AlphaFold 3 paper published in Nature.

References:
    ModelCIF dictionary: https://github.com/ihmwg/ModelCIF
    mmCIF format: https://mmcif.wwpdb.org/
"""

from beartype.typing import Mapping, Sequence

import numpy as np

from importlib.metadata import version

# Get the current version of the alphafold3_pytorch package
alphafold_version = version("alphafold3_pytorch")

# Legal disclaimer for AlphaFold predictions
# This disclaimer emphasizes that predictions are theoretical models, not validated
# for clinical use, and should be used with appropriate scientific caution
_DISCLAIMER = """THE INFORMATION IS NOT INTENDED FOR, HAS NOT BEEN VALIDATED FOR, AND IS NOT
APPROVED FOR CLINICAL USE. IT SHOULD NOT BE USED FOR CLINICAL PURPOSE OR RELIED
ON FOR MEDICAL OR OTHER PROFESSIONAL ADVICE. IT IS THEORETICAL MODELLING ONLY
AND CAUTION SHOULD BE EXERCISED IN ITS USE. IT IS PROVIDED "AS-IS" WITHOUT ANY
WARRANTY OF ANY KIND, WHETHER EXPRESSED OR IMPLIED. NO WARRANTY IS GIVEN THAT
USE OF THE INFORMATION SHALL NOT INFRINGE THE RIGHTS OF ANY THIRD PARTY."""

# Authors of the AlphaFold 3 Nature paper
# These organizations developed and published the AlphaFold 3 methodology
_MMCIF_PAPER_AUTHORS = (
    "Google DeepMind",
    "Isomorphic Labs",
)

# Authors listed in the mmCIF structure file
# Set to match the paper authors for proper attribution
_MMCIF_AUTHORS = _MMCIF_PAPER_AUTHORS


def add_metadata_to_mmcif(
    old_cif: Mapping[str, Sequence[str]], insert_alphafold_mmcif_metadata: bool = True
) -> Mapping[str, Sequence[str]]:
    """Add AlphaFold-specific metadata to an mmCIF dictionary.

    This function enriches an mmCIF dictionary with AlphaFold-specific metadata including:
    - ModelCIF compliance information
    - Software details (AlphaFold version, classification)
    - Citation to the AlphaFold 3 Nature paper
    - Author information
    - License and disclaimer
    - Quality assessment metrics (global pLDDT)
    - Protocol/methodology steps
    - Target entity descriptions

    Args:
        old_cif: The original mmCIF dictionary containing structure data, with keys
            like "_atom_site.B_iso_or_equiv", "_struct_asym.id", etc.
        insert_alphafold_mmcif_metadata: If True, includes full AlphaFold-specific
            metadata (software info, citations, quality metrics). If False, only
            includes minimal entity information. Default is True.

    Returns:
        A new dictionary containing the metadata fields to be merged with the original
        mmCIF data. The returned dictionary includes fields like:
        - _audit_conform.*: ModelCIF compliance information
        - _pdbx_data_usage.*: License and disclaimer
        - _audit_author.*: Structure authors
        - _citation.*: Paper citation details
        - _ma_data.*: Model data type
        - _ma_target_entity_instance.*: Entity instances
        - _ma_model_list.*: Model information
        - _software.*: AlphaFold software details
        - _ma_protocol_step.*: Modeling methodology
        - _ma_qa_metric.*: Quality assessment metrics
        - _ma_qa_metric_global.*: Global quality scores
        - _atom_type.symbol: Atomic symbols present in structure

    Example:
        >>> old_cif = {"_atom_site.B_iso_or_equiv": ["50.0", "60.0", "70.0"],
        ...            "_struct_asym.id": ["A"], "_struct_asym.entity_id": ["1"]}
        >>> metadata = add_metadata_to_mmcif(old_cif, insert_alphafold_mmcif_metadata=True)
        >>> "_software.name" in metadata
        True
        >>> metadata["_software.name"]
        ['AlphaFold']
    """
    # Initialize the metadata dictionary
    cif = {}

    if insert_alphafold_mmcif_metadata:
        # ModelCIF compliance information
        # Specifies the ModelCIF dictionary being used for model archiving
        # ModelCIF extends mmCIF for computational models and integrative structures
        cif["_audit_conform.dict_name"] = ["mmcif_ma.dic"]
        cif["_audit_conform.dict_version"] = ["1.4.5"]
        cif["_audit_conform.dict_location"] = [
            "https://raw.githubusercontent.com/ihmwg/ModelCIF/master/dist/" "mmcif_ma.dic"
        ]

        # License and disclaimer information
        # Entry 1: Non-commercial use license with terms of service reference
        # Entry 2: Medical/clinical use disclaimer warning
        cif["_pdbx_data_usage.id"] = ["1", "2"]
        cif["_pdbx_data_usage.type"] = ["license", "disclaimer"]
        cif["_pdbx_data_usage.details"] = [
            "NON-COMMERCIAL USE ONLY, BY USING THIS FILE YOU AGREE TO THE TERMS OF USE FOUND AT alphafoldserver.com/output-terms.",
            _DISCLAIMER,
        ]
        cif["_pdbx_data_usage.url"] = [
            "?",  # URL not specified
            "?",  # URL not specified
        ]

        # Structure author details
        # Lists the authors/organizations responsible for creating this structure
        cif["_audit_author.name"] = []
        cif["_audit_author.pdbx_ordinal"] = []
        for author_index, author_name in enumerate(_MMCIF_AUTHORS, start=1):
            cif["_audit_author.name"].append(author_name)
            cif["_audit_author.pdbx_ordinal"].append(str(author_index))

        # Paper citation author details
        # Lists authors of the primary citation (AlphaFold 3 Nature paper)
        cif["_citation_author.citation_id"] = []
        cif["_citation_author.name"] = []
        cif["_citation_author.ordinal"] = []
        for author_index, author_name in enumerate(_MMCIF_PAPER_AUTHORS, start=1):
            cif["_citation_author.citation_id"].append("primary")
            cif["_citation_author.name"].append(author_name)
            cif["_citation_author.ordinal"].append(str(author_index))

        # Primary paper citation details
        # Reference to the AlphaFold 3 paper in Nature (2024)
        # Note: Some fields are marked with "?" as they may not be finalized
        cif["_citation.id"] = ["primary"]
        cif["_citation.title"] = [
            "Accurate structure prediction of biomolecular interactions with AlphaFold 3"
        ]
        cif["_citation.journal_full"] = ["Nature"]
        cif["_citation.journal_volume"] = ["?"]  # To be filled when available
        cif["_citation.page_first"] = ["?"]      # To be filled when available
        cif["_citation.page_last"] = ["?"]       # To be filled when available
        cif["_citation.year"] = ["2024"]
        cif["_citation.journal_id_ASTM"] = ["NATUAS"]  # ASTM journal code for Nature
        cif["_citation.country"] = ["UK"]
        cif["_citation.journal_id_ISSN"] = ["0028-0836"]  # ISSN for Nature
        cif["_citation.journal_id_CSD"] = ["0006"]  # CSD journal code
        cif["_citation.book_publisher"] = ["?"]
        cif["_citation.pdbx_database_id_PubMed"] = ["?"]  # PubMed ID to be added
        cif["_citation.pdbx_database_id_DOI"] = ["?"]     # DOI to be added

        # Model data type description
        # Indicates this dataset contains predicted model coordinates
        cif["_ma_data.id"] = ["1"]
        cif["_ma_data.name"] = ["Model"]
        cif["_ma_data.content_type"] = ["model coordinates"]

    # Target entity instance information
    # Describes the number and details of each entity instance (chain) in the model
    cif["_ma_target_entity_instance.asym_id"] = old_cif["_struct_asym.id"]
    cif["_ma_target_entity_instance.entity_id"] = old_cif["_struct_asym.entity_id"]
    cif["_ma_target_entity_instance.details"] = ["."] * len(
        cif["_ma_target_entity_instance.entity_id"]
    )

    # Target entity details
    # Links each unique entity to the model data and provides origin information
    cif["_ma_target_entity.entity_id"] = cif["_ma_target_entity_instance.entity_id"]
    cif["_ma_target_entity.data_id"] = ["1"] * len(cif["_ma_target_entity.entity_id"])
    cif["_ma_target_entity.origin"] = ["."] * len(cif["_ma_target_entity.entity_id"])

    if insert_alphafold_mmcif_metadata:
        # Model list information
        # Describes the deposited model as the top-ranked prediction from AlphaFold
        cif["_ma_model_list.ordinal_id"] = ["1"]
        cif["_ma_model_list.model_id"] = ["1"]
        cif["_ma_model_list.model_group_id"] = ["1"]
        cif["_ma_model_list.model_name"] = ["Top ranked model"]

        cif["_ma_model_list.model_group_name"] = [f"AlphaFold v{alphafold_version}"]
        cif["_ma_model_list.data_id"] = ["1"]
        cif["_ma_model_list.model_type"] = ["Ab initio model"]  # Predicted from sequence

        # Software information
        # Details about the AlphaFold software used to generate the prediction
        cif["_software.pdbx_ordinal"] = ["1"]
        cif["_software.name"] = ["AlphaFold"]
        cif["_software.version"] = [f"v{alphafold_version}"]
        cif["_software.type"] = ["package"]
        cif["_software.description"] = ["Structure prediction"]
        cif["_software.classification"] = ["other"]
        cif["_software.date"] = ["?"]  # Release date to be specified

        # Software grouping
        # Groups the AlphaFold software into a single logical unit
        cif["_ma_software_group.ordinal_id"] = ["1"]
        cif["_ma_software_group.group_id"] = ["1"]
        cif["_ma_software_group.software_id"] = ["1"]

        # Modeling protocol steps
        # Describes the three main stages of AlphaFold prediction:
        # 1. Multiple sequence alignment for evolutionary information
        # 2. Template structure search (if applicable)
        # 3. Structure prediction/modeling
        cif["_ma_protocol_step.ordinal_id"] = ["1", "2", "3"]
        cif["_ma_protocol_step.protocol_id"] = ["1", "1", "1"]
        cif["_ma_protocol_step.step_id"] = ["1", "2", "3"]
        cif["_ma_protocol_step.method_type"] = [
            "coevolution MSA",    # Step 1: MSA generation
            "template search",     # Step 2: Template identification
            "modeling",           # Step 3: Structure prediction
        ]

        # Quality assessment metrics
        # Defines pLDDT (predicted Local Distance Difference Test) as the confidence metric
        # pLDDT is computed both globally (average over all residues) and locally (per residue)
        cif["_ma_qa_metric.id"] = ["1", "2"]
        cif["_ma_qa_metric.name"] = ["pLDDT", "pLDDT"]
        # Metric type (pLDDT-specific; accepted values: distance, energy, normalised score, other, zscore)
        cif["_ma_qa_metric.type"] = ["pLDDT", "pLDDT"]
        cif["_ma_qa_metric.mode"] = ["global", "local"]  # Global and local confidence
        cif["_ma_qa_metric.software_group_id"] = ["1", "1"]

        # Global confidence score
        # Calculate the average pLDDT across all atoms
        # pLDDT values are stored in the B-factor column (_atom_site.B_iso_or_equiv)
        # Higher values (0-100) indicate higher confidence in the prediction
        cif["_ma_qa_metric_global.ordinal_id"] = ["1"]
        cif["_ma_qa_metric_global.model_id"] = ["1"]
        cif["_ma_qa_metric_global.metric_id"] = ["1"]
        global_plddt = np.mean([float(v) for v in old_cif["_atom_site.B_iso_or_equiv"]])
        cif["_ma_qa_metric_global.metric_value"] = [f"{global_plddt:.2f}"]

    # Atom type symbols
    # Extract and sort unique chemical element symbols present in the structure
    cif["_atom_type.symbol"] = sorted(set(old_cif["_atom_site.type_symbol"]))

    return cif
